catalog/urls.py
from django.urls import path

from catalog.views import (
    index,
    LiteraryFormatListView,
    LiteraryFormatCreateView,
    LiteraryFormatUpdateView,
    LiteraryFormatDeleteView,
    BookListView,
    AuthorListView,
    BookDetailView,
    AuthorDetailView,
    test_session_view,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "literary-format/",
        LiteraryFormatListView.as_view(),
        name="literary-format-list"
    ),
    path(
        "literary-format/create/",
        LiteraryFormatCreateView.as_view(),
        name="literary-format-create"
    ),
    path(
        "literary-format/<int:pk>/update/",
        LiteraryFormatUpdateView.as_view(),
        name="literary-format-update"
    ),
    path(
        "literary-format/<int:pk>/delete/",
        LiteraryFormatDeleteView.as_view(),
        name="literary-format-delete"
    ),
    path(
        "books/",
        BookListView.as_view(),
        name="book-list"
    ),
    path(
        "books/<int:pk>/",
        BookDetailView.as_view(),
        name="book-detail"
    ),
    path(
        "authors/",
        AuthorListView.as_view(),
        name="author-list"
    ),
    path(
        "authors/<int:pk>/",
        AuthorDetailView.as_view(),
        name="author-detail"
    ),
    path(
        "test-session/",
        test_session_view,
        name="test-session"
    )
]

app_name = "catalog"

library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class LiteraryFormat(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Author(AbstractUser):
    pseudonym = models.CharField(max_length=63, null=True, blank=True)

    class Meta:
        ordering = ["username"]

    def get_absolute_url(self):
        return reverse("catalog:author-detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Book(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    format = models.ForeignKey(
        LiteraryFormat,
        on_delete=models.CASCADE,
        related_name="books",
    )
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="books")

    class Meta:
        ordering = ["title"]

    def get_absolute_url(self):
        return reverse("catalog:book-detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.title} (price: {self.price}, format: {self.format.name})"

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from catalog.models import Book, Author, LiteraryFormat


@login_required
def index(request):
    num_books = Book.objects.count()
    num_authors = Author.objects.count()
    num_literary_formats = LiteraryFormat.objects.count()

    num_visit = request.session.get("num_visit", 0)
    request.session["num_visit"] = num_visit + 1

    context = {
        "num_books": num_books,
        "num_authors": num_authors,
        "num_literary_formats": num_literary_formats,
        "num_visit": num_visit + 1,
    }

    return render(request, "catalog/index.html", context=context)


class LiteraryFormatListView(LoginRequiredMixin, generic.ListView):
    model = LiteraryFormat
    template_name = "catalog/literary_format_list.html"
    context_object_name = "literary_format_list"
    # queryset = LiteraryFormat.objects.filter(name__endswith="y")

# def literary_format_list_view(request):
#     literary_format_list = LiteraryFormat.objects.all()
#
#     context = {
#         "literary_format_list": literary_format_list
#     }
#
#     return render(request, "catalog/literary_format_list.html", context=context)


class LiteraryFormatCreateView(LoginRequiredMixin, generic.CreateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary-format-list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary-format-list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = LiteraryFormat
    success_url = reverse_lazy("catalog:literary-format-list")
    template_name = "catalog/literary_format_confirm_delete.html"


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    queryset = Book.objects.all().select_related("format")
    paginate_by = 1


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book

# def book_detail_view(request, pk):
#     try:
#         book = Book.objects.get(pk=pk)
#     except Book.DoesNotExist:
#         raise Http404("Book does not exist")
#
#     context = {
#         "book": book
#     }
#
#     return render(request, "catalog/book_detail.html", context=context)


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author
    queryset = Author.objects.all().prefetch_related("books__format")


def test_session_view(request):
    return HttpResponse(
        "<h1>Test Session</h1>"
        f"<h4>Session data: {request.session['book']}</h4>"
    )

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {% block title %}
    <title>Library</title>
  {% endblock %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}
      </div>
       <div class="col-sm-9">
         {% block content %}{% endblock %}
         {% block pagination %}
           {% include "includes/pagination.html" %}
         {% endblock %}
       </div>
    </div>
  </div>


</body>
</html>

templates/catalog/author_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ author.first_name }} {{ author.last_name }}</h1>
    <p><strong>Username:</strong> {{ author.username }}</p>
    <p><strong>Is Staff:</strong> {{ author.is_staff}}</p>
    <p>{% if author.pseudonym %} <strong>Pseudonym:</strong> {{ author.pseudonym }}{% endif %}</p>
    <div class="ml-3">
      <h3>Books</h3>
        {% for book in author.books.all %}
          <hr>
          <p class="text-muted"><strong>Id:</strong> {{ book.id }}</p>
          <p><strong>Title:</strong> {{ book.title }}</p>
          <p><strong>Format:</strong> {{ book.format }}</p>
        {% empty %}
          <p>No books!</p>
        {% endfor %}
    </div>
{% endblock %}

templates/catalog/author_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Authors List</h1>
    {% if author_list %}
    <ul>
      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.username }} ({{ author.first_name }} {{ author.last_name }})</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>There are no authors in library</p>
    {% endif %}
{% endblock %}

templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>
    <p><strong>Price:</strong> {{ book.price }}</p>
    <p><strong>Format:</strong> {{ book.format.name }}</p>
    <div class="ml-3">
      <h3>Authors</h3>
        {% for author in book.authors.all %}
          <hr>
          <p class="text-muted"><strong>Id:</strong> {{ author.id }}</p>
          <p>
            <strong>Full name:</strong> {{ author.first_name }} {{ author.last_name }}
            {% if author.pseudonym %}({{ author.pseudonym }}){% endif %}
          </p>
        {% empty %}
          <p>No authors!</p>
        {% endfor %}
    </div>
{% endblock %}

templates/catalog/book_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Books List</h1>
  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li>
          <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
           (price: {{ book.price }}, format: {{ book.format }})
        </li>
    {% endfor %}
    </ul>
  {% else %}
    <p>There are no books in library</p>
  {% endif %}
{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Library Home</h1>
  <p>Welcome to the Greatest Library</p>
  <h3>Library content:</h3>
  <ul>
    <li>Num books: {{ num_books }}</li>
    <li>Num authors: {{ num_authors }}</li>
    <li>Num literary formats: {{ num_literary_formats }}</li>
  </ul>
  <p>You visited this page {{ num_visit }} time{{ num_visit|pluralize }}.</p>
{% endblock %}

templates/catalog/literary_format_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Literary Format</h1>

  <p>Are you sure you want to delete the literary format: <strong>{{ literaryformat }}</strong></p>
  <p>All Books with this literary format will be deleted!</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger" />
  </form>
{% endblock %}

templates/catalog/literary_format_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Literary Format</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/literary_format_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Literary Format</h1>
  {% if literary_format_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    
      {% for literary_format in literary_format_list %}
        <tr>
          <td>
            {{ literary_format.id }}
          </td>
          <td>
            {{ literary_format.name }}
          </td>
          <td>
            <a href="{% url 'catalog:literary-format-update' pk=literary_format.id%}">Update</a>
          </td>
          <td>
            <a href="{% url 'catalog:literary-format-delete' pk=literary_format.id%}">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no literary formats in library</p>
  {% endif %}
  <p><a href="{% url 'catalog:literary-format-create' %}">Add+</a></p>
{% endblock %}

templates/includes/pagination.html
  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?page={{ page_obj.previous_page_number }}" class="page-link">prev</a>
        </li>
      {% endif %}

      <li class="page-item active">
          <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>

      {% if page_obj.has_next%}
        <li class="page-item">
          <a href="?page={{ page_obj.next_page_number }}" class="page-link">next</a>
        </li>
      {% endif %}
      </ul>
  {% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav">
  {% if user.is_authenticated %}
    <li>User: {{ user.username }}</li>
    <li><a href="{% url 'logout' %}">Logout</a></li>
  {% else %}
    <li><a href="{% url 'login' %}">Login</a></li>
  {% endif %}
  <br>
  <li><a href="{% url 'catalog:index' %}">Home</a></li>
  <li><a href="{% url 'catalog:author-list' %}">All authors</a></li>
  <li><a href="{% url 'catalog:book-list' %}">All books</a></li>
  <li><a href="{% url 'catalog:literary-format-list' %}">All literary formats</a></li>
</ul>